# Generated by Django 2.2.6 on 2020-03-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('FILE', 'File'), ('SCREEN', 'Screen')], default='FILE', max_length=100)),
                ('loop', models.BooleanField(default=True)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'paused'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='RUNNING', max_length=100)),
                ('completed', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
