# Generated by Django 2.2.6 on 2020-04-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('RTMP', 'RTMP'), ('RTC', 'RTC')], default='RTMP', max_length=10),
        ),
    ]
